version: '3.8'

services:
  api:
    build:
      context: ./src
      dockerfile: Hotelaria.Server/Dockerfile
    container_name: hotelaria-api
    ports:
      - "5000:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=meubanco;user=admin;password=123456

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: meubanco
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
